export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';
export const SET_POST_NOT_FOUND = 'SET_POST_NOT_FOUND';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const SHOW_EDIT_POST = 'SHOW_POST';
export const CLOSE_EDIT_POST = 'CLOSE_EDIT_POST';
export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE';
